[2025-01-24T09:01:38.833+0900] {processor.py:186} INFO - Started process (PID=12566) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:01:38.834+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:01:38.835+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:01:38.834+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:01:41.319+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:01:41.318+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:01:41.320+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:01:41.331+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.503 seconds
[2025-01-24T09:04:15.487+0900] {processor.py:186} INFO - Started process (PID=12998) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:04:15.495+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:04:15.496+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:04:15.495+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:04:18.076+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:04:18.075+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:04:18.076+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:04:18.090+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.606 seconds
[2025-01-24T09:06:45.348+0900] {processor.py:186} INFO - Started process (PID=13431) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:06:45.355+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:06:45.357+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:06:45.356+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:06:47.950+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:06:47.949+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:06:47.950+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:06:47.963+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.619 seconds
[2025-01-24T09:09:20.236+0900] {processor.py:186} INFO - Started process (PID=13860) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:09:20.237+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:09:20.238+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:09:20.238+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:09:22.763+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:09:22.762+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:09:22.764+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:09:22.776+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.544 seconds
[2025-01-24T09:11:51.363+0900] {processor.py:186} INFO - Started process (PID=14290) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:11:51.364+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:11:51.365+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:11:51.365+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:11:54.273+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:11:54.272+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:11:54.274+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:11:54.286+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.927 seconds
[2025-01-24T09:14:25.832+0900] {processor.py:186} INFO - Started process (PID=14720) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:14:25.840+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:14:25.841+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:14:25.840+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:14:28.355+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:14:28.355+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:14:28.356+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:14:28.368+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.540 seconds
[2025-01-24T09:17:00.668+0900] {processor.py:186} INFO - Started process (PID=15149) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:17:00.676+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:17:00.677+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:17:00.677+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:17:03.228+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:17:03.227+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:17:03.229+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:17:03.241+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.576 seconds
[2025-01-24T09:19:35.620+0900] {processor.py:186} INFO - Started process (PID=15579) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:19:35.627+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:19:35.628+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:19:35.628+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:19:38.084+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:19:38.083+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:19:38.085+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:19:38.095+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.480 seconds
[2025-01-24T09:22:09.008+0900] {processor.py:186} INFO - Started process (PID=16009) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:22:09.009+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:22:09.010+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:22:09.010+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:22:11.699+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:22:11.698+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:22:11.699+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:22:11.712+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.708 seconds
[2025-01-24T09:24:44.737+0900] {processor.py:186} INFO - Started process (PID=16448) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:24:44.744+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:24:44.745+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:24:44.745+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:24:47.242+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:24:47.242+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:24:47.243+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:24:47.254+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.521 seconds
[2025-01-24T09:27:14.858+0900] {processor.py:186} INFO - Started process (PID=16877) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:27:14.865+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:27:14.866+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:27:14.866+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:27:17.251+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:27:17.250+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:27:17.252+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:27:17.263+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.409 seconds
[2025-01-24T09:29:38.402+0900] {processor.py:186} INFO - Started process (PID=17296) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:29:38.409+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:29:38.410+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:29:38.410+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:29:41.125+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:29:41.125+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:29:41.126+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:29:41.141+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.744 seconds
[2025-01-24T09:32:36.276+0900] {processor.py:186} INFO - Started process (PID=17749) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:32:36.284+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:32:36.286+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:32:36.285+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:32:39.186+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:32:39.186+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:32:39.187+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:32:39.201+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.931 seconds
[2025-01-24T09:35:33.308+0900] {processor.py:186} INFO - Started process (PID=18196) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:35:33.309+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:35:33.310+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:35:33.310+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:35:36.212+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:35:36.211+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:35:36.213+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:35:36.226+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.925 seconds
[2025-01-24T09:38:25.576+0900] {processor.py:186} INFO - Started process (PID=18620) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:38:25.584+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:38:25.586+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:38:25.585+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:38:28.497+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:38:28.497+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:38:28.498+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:38:28.515+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.948 seconds
[2025-01-24T09:41:24.050+0900] {processor.py:186} INFO - Started process (PID=19055) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:41:24.057+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:41:24.058+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:41:24.058+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:41:26.880+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:41:26.879+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:41:26.880+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:41:26.895+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.852 seconds
[2025-01-24T09:44:15.446+0900] {processor.py:186} INFO - Started process (PID=19479) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:44:15.447+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:44:15.449+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:44:15.449+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:44:18.241+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:44:18.241+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:44:18.242+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:44:18.255+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.817 seconds
[2025-01-24T09:47:04.210+0900] {processor.py:186} INFO - Started process (PID=19903) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:47:04.218+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:47:04.219+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:47:04.219+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:47:07.045+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:47:07.044+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:47:07.045+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:47:07.061+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.859 seconds
[2025-01-24T09:50:00.787+0900] {processor.py:186} INFO - Started process (PID=20337) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:50:00.794+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:50:00.796+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:50:00.796+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:50:03.723+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:50:03.722+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:50:03.724+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:50:03.737+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.959 seconds
[2025-01-24T09:53:00.487+0900] {processor.py:186} INFO - Started process (PID=20762) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:53:00.495+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:53:00.496+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:53:00.496+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:53:03.305+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:53:03.304+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:53:03.307+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:53:03.321+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.840 seconds
[2025-01-24T09:55:58.354+0900] {processor.py:186} INFO - Started process (PID=21196) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:55:58.355+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:55:58.356+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:55:58.356+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:56:01.333+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:56:01.332+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:56:01.333+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:56:01.347+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.999 seconds
[2025-01-24T09:58:59.337+0900] {processor.py:186} INFO - Started process (PID=21630) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:58:59.345+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T09:58:59.347+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:58:59.347+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:59:02.442+0900] {logging_mixin.py:190} INFO - [2025-01-24T09:59:02.441+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T09:59:02.443+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T09:59:02.455+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 3.127 seconds
[2025-01-24T10:01:54.205+0900] {processor.py:186} INFO - Started process (PID=22055) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:01:54.212+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T10:01:54.213+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:01:54.213+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:01:57.537+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:01:57.536+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T10:01:57.537+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:01:57.550+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 3.354 seconds
[2025-01-24T10:04:54.489+0900] {processor.py:186} INFO - Started process (PID=22489) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:04:54.490+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T10:04:54.492+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:04:54.491+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:04:57.531+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:04:57.530+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T10:04:57.533+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:04:57.546+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 3.064 seconds
[2025-01-24T10:07:53.809+0900] {processor.py:186} INFO - Started process (PID=22923) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:07:53.817+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T10:07:53.819+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:07:53.819+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:07:57.345+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:07:57.345+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T10:07:57.346+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:07:57.359+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 3.556 seconds
[2025-01-24T10:10:56.184+0900] {processor.py:186} INFO - Started process (PID=23358) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:10:56.191+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T10:10:56.193+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:10:56.192+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:10:59.337+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:10:59.336+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T10:10:59.338+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:10:59.351+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 3.176 seconds
[2025-01-24T10:13:58.697+0900] {processor.py:186} INFO - Started process (PID=23793) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:13:58.704+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T10:13:58.706+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:13:58.706+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:14:01.796+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:14:01.795+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T10:14:01.797+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:14:01.812+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 3.121 seconds
[2025-01-24T10:16:55.863+0900] {processor.py:186} INFO - Started process (PID=24227) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:16:55.871+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T10:16:55.872+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:16:55.872+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:16:58.787+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:16:58.786+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T10:16:58.788+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:16:58.801+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.944 seconds
[2025-01-24T10:19:54.833+0900] {processor.py:186} INFO - Started process (PID=24661) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:19:54.841+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T10:19:54.842+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:19:54.842+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:19:57.790+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:19:57.789+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T10:19:57.791+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:19:57.805+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.977 seconds
[2025-01-24T10:22:49.815+0900] {processor.py:186} INFO - Started process (PID=25086) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:22:49.822+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T10:22:49.824+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:22:49.823+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:22:53.105+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:22:53.104+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T10:22:53.106+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:22:53.120+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 3.311 seconds
[2025-01-24T10:25:47.287+0900] {processor.py:186} INFO - Started process (PID=25510) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:25:47.288+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T10:25:47.290+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:25:47.289+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:25:50.339+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:25:50.338+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T10:25:50.340+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:25:50.362+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 3.085 seconds
[2025-01-24T10:28:38.683+0900] {processor.py:186} INFO - Started process (PID=25957) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:28:38.690+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T10:28:38.691+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:28:38.691+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:28:41.346+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:28:41.345+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T10:28:41.346+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:28:41.358+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.679 seconds
[2025-01-24T10:31:13.231+0900] {processor.py:186} INFO - Started process (PID=26376) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:31:13.239+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T10:31:13.240+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:31:13.239+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:31:15.721+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:31:15.721+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T10:31:15.722+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:31:15.735+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.509 seconds
[2025-01-24T10:33:47.236+0900] {processor.py:186} INFO - Started process (PID=26791) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:33:47.237+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T10:33:47.238+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:33:47.238+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:33:49.632+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:33:49.631+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T10:33:49.632+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:33:49.643+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.412 seconds
[2025-01-24T10:36:14.297+0900] {processor.py:186} INFO - Started process (PID=27219) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:36:14.302+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T10:36:14.304+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:36:14.303+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:36:16.811+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:36:16.810+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T10:36:16.812+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:36:16.824+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.531 seconds
[2025-01-24T10:39:00.186+0900] {processor.py:186} INFO - Started process (PID=27766) to work on /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:39:00.187+0900] {processor.py:914} INFO - Processing file /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py for tasks to queue
[2025-01-24T10:39:00.188+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:39:00.187+0900] {dagbag.py:588} INFO - Filling up the DagBag from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:39:02.716+0900] {logging_mixin.py:190} INFO - [2025-01-24T10:39:02.715+0900] {dagbag.py:387} ERROR - Failed to import: /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
Traceback (most recent call last):
  File "/home/harry/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py", line 34, in <module>
    from utils.Prediction import run_prediction #TimeSeriesDataset, GRUModel, GRUWithAttention
ModuleNotFoundError: No module named 'utils.Prediction'
[2025-01-24T10:39:02.716+0900] {processor.py:927} WARNING - No viable dags retrieved from /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py
[2025-01-24T10:39:02.729+0900] {processor.py:208} INFO - Processing /home/harry/airflow/dags/.ipynb_checkpoints/my_backcup-checkpoint.py took 2.547 seconds
